### ISSUE TITLE
NPM package.json formatter

### ISSUE THREAD

**Issue by muuvmuuv** [Unibeautify/beautifier-sort-package-json#1]
**Beautifier Details**
Name: sort-package-json
Link to project/homepage: https://github.com/keithamus/sort-package-json

**If this is a new beautifier, please fill out the below**
Languages Supported: package.json (only)
How is it run (node, terminal, etc): node

**Additional context**

I think this formatter could be a good thing to keep package.json files formatted correctly in all projects or everytime someone edit them manually. I use it daily to keep them clean when "Pretty Diff" is formatting them a little bit different.

I think @Glavin001 commented some day that I should keep the line break in the arrays, this would fix this problem, because Pretty Diff always keep them on one line.

```json
{
  "dependencies": {},
  "version": "1.0.0",
  "keywords": ["thing"],
  "name": "foo",
}
```
after

```json
{
  "name": "foo",
  "version": "1.0.0",
  "keywords": ["thing"],
  "dependencies": {}
}
```

**Comment by Glavin001** [comment]
@muuvmuuv repository created and all yours to take this on 🎉 . Thanks for the great idea and for contributing! 😃
